version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "8080:80"
    # Optionnel : pour rebuilder automatiquement en dev
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
